### PR TITLE
Mod Menu + Original/Ryukishi Mode + Misc changes

### PR DESCRIPTION
**Pull request by drojf**
So, I got a bit carried away and included many fixes all in this one branch. There is also some refactoring of existing code (related to the mod toggles and keyboard inputs).

I've already did merges against all the other branches (to check it could merge reasonably).

To allow the DLLs to be tested, I've added them to the installer as an option (the very latest commit with the "quitaftercompile" command line argument is not in the DLL though). That's probably the easiest way to check these changes out.

One thing of note is that in the code I have used the word "Ryukishi" for original mode, rather than the word "Original". But the mod menu text still says "Ryukishi/Original" mode on the user facing side so it's more clear.

Please don't merge this PR until the new DLL has been tested for a while.

## Mod Menu

- Add an in-game mod menu
- Add changing the opening movie flag in the menu
- Add ability to select any combination of assets
  - You can toggle between ADV, NVL, and OG mode
  - You can also set which artset to use
  - Finally, you can override the current background used, regardless of artset
  - Using combinations of these three options, you can set any combination of backgrounds, sprites, and text display/image cropping
- Add buttons to show the log folder, save folder, and CompiledUpdateScripts folder, and open the 07th-mod support page
- Add option to set custom (16:9) resolutions
- Add Mod menu resolution scaling (tested from 480p to 1440p)
- Fix clicks passing through the mod menu
- Add ability to open menu via button on the "config" page, as well as the F10 key
- Add ability to close menu with F10, the 'X' button, or right clicking

## Misc

- Add playback of an example voice file when the voice volume is adjusted via keyboard, so it's easier to check how loud you've set it
- Add toast notification when changing an option using a keyboard shortcut (so it's clear when an option has been changed)
- Fix crash if image asset is missing (in certain cases), by returning dumy texture instead 134d369d60c4723496b8efd9d3defdef5617d1b1
- Add error menu/error message shown if the game fails to start up 1aa7e4886f55942059484d82376f41f716232d05, or saves are corrupted 4e22c90eb347c369fd114c8db5222de3c30c7809 (rather than a black screen as previously)

## Developer

- Refactor mod hotkey handling so that can detect if a button was pressed, but no action could be taken due to the game being in the middle of animating
- Add "quitaftercompile" function so that game can be used for automated script compilation 6c08d94eafa6254130f1322be02a1ef8ac5f16fc
  - if "quitaftercompile" is passed as command line argument, game will quit after compilation is finished
  - will also write out the file "higu_script_compile_status.txt" to current directory to differentiate between the game crashing and scripts finishing to compile

## Original/Ryukishi Mode

- Display in 4:3 aspect instead of 16:9 (with exceptions, see below)
- Crop sprites if they extend beyond 4:3 (any images in the sprites folder drawn with bustshot command) 
  - 42da17ed2d570b3b81ef8d40996efe145ec2a680
  - 3a486754c88e6a5c1dd43cac238d3e4eff092422
  - b9e26ccc1f9389268081b8004ef6c7791a4a9612
- Add option to skip CGs, enabled by default when OG mode is enabled
- Display any background images which are still 16:9 in 16:9. This is done so that any text assets will still be readable even if we don't resize them.
- Add option to stretch backgrounds, disabled by default

## (Optional) Script functions added

The following functions were added, but are not necessary (current scripts will still work even without these functions called, using the hardcoded default values). They are usually called from `init.txt` and mirror the existing functions with similar names.

- ModRyukishiSetGuiPosition - This mirrors the existing SetGuiPosition script function. It sets the GUI position when in Original/Ryukishi mode
- ModRyukishiModeSettingLoad - This mirrors the existing ModADVModeSettingLoad. It sets the window position etc. for Original/Ryukishi mode

### CODE REVIEW

**Comment by drojf** [comment]
It was reported that the characters sometimes "escape" the 4:3 window on the new DLL on certain scenes ("The bug disappeared after the 9th chapter was finished"). May be worth looking into

**Comment by drojf** [comment]
I'm planning to merge this pull request (and then update all the DLLs by merging `mod` into them). I'm fairly certain it's stable as it's been tested for a while (and in the last twoish weeks has been the default DLL).

Is there anything I should know/check/fix before/after merging this pull request?

Also note that the Travis checks are failing only on my branch, not on the pull request itself.

**Comment by tellowkrinkle** [comment]
We shouldn't be cropping sprites for this, it's the same issue as the one where the scrolling background goes off the screen on fullscreen 16:10 monitors

The proper solution is to get unity to do the equivalent of a glScissor with our camera, probably [this](https://docs.unity3d.com/ScriptReference/Camera-rect.html)

**Comment by drojf** [comment]
Hey tellow

The reason I did it this way was because I wanted any text background assets (like, images which are just text on a white background) we have which are in 16:9 to still be fully displayed (as otherwise we'd have to re-do all the text assets in 4:3, or squish them to 4:3). 

I actually initially implemented the 4:3 mode by changing the game resolution to a 4:3 resolution (which worked), but it would mean 16:9 text assets would be chopped off on a 16:9 screen.

As far as I understand it, the link you posted would affect everything on screen, so it wouldn't allow the display of 16:9 text assets, but if there is a way to selectively apply a glScissor like thing only to the sprites I would be interested to know.

**Pull request merged**
