### PR TITLE
support for extra adv textbox

### PR DESCRIPTION
**Pull request by Adam-M93**
i closed the previous pr as i noticed problems when moving between days, which seemed to be from the audio switch stuff i did, i decided to just scrap it and deleted the branch and started from scratch and only did textbox stuff. im not really happy with the method as each textbox would need to be added seperately in the dll, but it works. having it done outside the dll like how tips is done would probably be better, but i don't know how to do that right now

below is from previous pr
As mentioned in discord, I looked at adding multi adv textbox support and managed to get somewhere with it https://gfycat.com/craftysoupyarabianoryx

in init.txt
```
    ModADVModeTextbox2SettingLoad(
        "<size=+4>{0}\n</size>", //NameFormat
        -170, //WindowPosX
        -300, //WindowPosY
        1150, //WindowSizeX
        250, //WindowSizeY
        60, //WindowMarginLeft
        30, //WindowMarginTop
        50, //WindowMarginRight
        30, //WindowMarginBottom
        1, //FontID
        0, //CharSpacing
        8, //LineSpacing
        28 //FontSize
    );
```
needs to be added.
The new textbox needs to be windo_filter_adv2.png and old windo_filter_adv.png

Toggle button is T.

### CODE REVIEW

**Comment by enumag** [comment]
@idealpersona @tellowkrinkle Take a look at this when you have some time. The ability to switch textboxes would be very nice to have.

**Review by TellowKrinkle — CHANGES_REQUESTED** [review]
A few things on the commit as a whole
- If you could rebase your changes to be off the `mod` branch that would be great
- Not sure how this happened, but somehow all the line endings in your commit are CRLF instead of LF.  I thought Git automatically dealt with this but I guess not.  I'll try to get a configuration file in to tell git to do it correctly but for now could you convert the line endings to unix for now?  That should clear up the weird lines that look like they're identical but are marked as changed in the git log.  (If you do `git config core.autocrlf true` on windows Git will checkout files with CRLF and then convert back to LF when you commit, if you then `git reset HEAD~` redo the commit, and push with `--force` afterward that should clear everything up.)

Other than that it looks fine, though we should decide whether we want to be adding support for one more text box or adding support for a variable number (AKA do we expect to have to do this again)

**Comment by enumag** [comment]
> we should decide whether we want to be adding support for one more text box or adding support for a variable number (AKA do we expect to have to do this again)

We definitely want a variable number.

Here are my thoughts how it could work:

1. NVL/ADV mode distinction would disappear, it would just be different textboxes.
2. Each textbox should have a `textbox.png` file, a `config.json` file and optionally a `textbox_alt.png` file.
3. `textbox.png` would be the equivalent of current `windo_filter.png`.
4. `config.json` would hold this [configuration](https://github.com/07th-mod/onikakushi/blob/61a9789689b1ec154ce0f2d78bdaf0d6e4287bc3/Update/init.txt#L76-L90)
5. `textbox_alt.png` should be switched to when `ModEnableNVLModeInADVMode()` is used (could be renamed). In this case the `config.json` should hold a secondary configuration for this file too.
6. If `textbox_alt.png` does not exist for the currently used textbox then `ModEnableNVLModeInADVMode()` should have no effect.
7. Configuration should also hold a new flag to determine the behaviour of `GLinemodeSp`. This is now different in NVL / ADV.

Directory structure maybe something like this?

```
CG/
    textbox/
        1/
            textbox.png
            textbox_alt.png
            config.json
        2/
            textbox.png
            config.json
```

**Comment by idealpersona** [comment]
Good comments Tellow.

I'm only taking a glance at all this so I haven't really thought it through yet.  But i feel some hesitation at throwing the text box image files and their configs together in the CG folder.  The assets and configs would be best separated unless the text boxes were in their own `TextBoxes` folder in the top-level data directory rather than in CG. But I don't know whether that plays nice with asset file loading.  Also I feel that these configs can easily live within the general json config file which is already quite small - only a few settings last I remember. so like nipah.json `{... "textBoxes": [ { /* settings */ } ] ...}` or `{... "textBoxes": { 0 : { /* settings */ } } ...}` or whatever.  And in this case the text boxes are quite nice to leave in CG.  But it's not a big deal if turns out significantly easier to structure it any particular way.

Of course no matter what we have to do this in every arc repo.  It would be nice to only have to do stuff like this once like the assembly repo somewhat is now with the branching, but that's probably another conversation.

**Comment by enumag** [comment]
@idealpersona Yeah, I agree that having the config in CG is not best, separate TextBoxes directory could indeed be better. I don't think it would cause a problem.

The reason why I slightly prefer separate config files is modularity - that way anyone can create their own textbox and publish it as a zip. But I don't expect many people to actually do that so I don't have any strong feelings about this. Still I'd like to have textboxes configuration separate from any game-specific configuration so that we can distribute all textboxes as one archive that will be the same for all arcs - this mitigates your last paragraph too.

**Comment by idealpersona** [comment]
With this in mind I like the idea of having everything in one folder like that if we are able to have a TextBoxes folder in the data directory.

If nvl / adv are truly just different values for the same parameters and the same code, then yeah we can drop it.  But i have seen a lot of code that branches on a NVL_IN_ADV check at least. And I assume F1 would just cycle through text boxes in this case?

**Comment by Adam-M93** [comment]
I did some changes and also put it on mod-textbox branch, I've not merged it into oni-mod-textbox yet. https://github.com/Adam-M93/higurashi-assembly/tree/mod-textbox

- F1 now cycles between Textbox 1 (NVL), Textbox 2 (Old ADV), Textbox 3 (New ADV). GADVMode is enabled for textbox 1 and disabled for others. T hotkey is removed
- Files should be Unix EOL now (I hate EOL stuff)
- 'ADVModeTextbox2' now 'Textbox3'
- GADVTextbox flag now GTextbox
- Textboxes are now in Textbox folder of CG
Example: Textbox 1 = CG\Textbox\1\textbox.png

comparison link
https://github.com/07th-mod/higurashi-assembly/compare/mod...Adam-M93:mod-textbox

About the ModTextBoxSettings class mentioned, I'm assuming instead of multiple strings/ints and methods for each textbox style it would just be 2 methods, 1 for storing and 1 for loading, and the strings/ints for those methods, but I don't know how to go about getting that working so I'd need help for that if you don't mind.

I'm not sure if it's possible to change the PR branches or if a new PR would have to be made.

**Pull request closed without merging**
